using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HAGOServiceKey
{
	public const string PARAM_ID = "id";
	public const string PARAM_IMAGE = "image";
	public const string PARAM_NAME = "name";
	public const string PARAM_TYPE = "type";
	public const string PARAM_DESCRIBE = "describe";
	public const string PARAM_STATUS = "status";
	public const string PARAM_QUANTITY = "quantity";
	public const string PARAM_IMAGE_THUMB = "image_thumb";
	public const string PARAM_CONNECT_TYPE = "connect_type";
	public const string PARAM_VSM_STATS = "vsm_stats";
	public const string PARAM_SERVICE_UUID = "service_uuid";
	public const string PARAM_CHARACTERISTIC_UUID = "characteristic_uuid";
	public const string PARAM_DISPLAY_NAME = "display_name";
    public const string PARAM_KEY_FORM = "key_form";
    public const string PARAM_TITLE = "title";
    public const string PARAM_DATA = "data";
    public const string PARAM_RESOURCE = "resource";
    public const string PARAM_URL = "url";
    public const string PARAM_VALUE = "value";
    public const string PARAM_OPTIONS = "options";
    public const string PARAM_OPTION = "option";
    public const string PARAM_DEFAULT_VALUE = "default_value";
    public const string PARAM_ICON = "icon";
    public const string PARAM_IS_VSM = "is_vsm";
    public const string PARAM_FORM_ID = "form_id";
    public const string PARAM_DESC = "desc";
    public const string PARAM_FORM_DATA = "form_data";
    public const string PARAM_DISCLAIMER_DATA = "disclaimer_data";
    public const string PARAM_TERMS_CONTENT = "terms_content";
    public const string PARAM_TOGGLE_CONTENT = "toggle_content";
    public const string PARAM_CONTENT = "content";
    public const string PARAM_PLACEHOLDER = "placeholder";
    public const string PARAM_CONTENT_TYPE = "content_type";
    public const string PARAM_UNIT = "unit";
    public const string PARAM_MIN_LENGTH = "min_length";
    public const string PARAM_MAX_LENGTH = "max_length";
    public const string PARAM_MIN_VALUE = "min_value";
    public const string PARAM_MAX_VALUE = "max_value";
    public const string PARAM_INTEGER = "integer";
    public const string PARAM_DECIMAL = "decimal";
    public const string PARAM_STANDARD = "standard";
    public const string PARAM_IHEALTH_SDK = "ihealth_sdk";
    public const string PARAM_STANDARD_PROFILE = "standard_profile";
    public const string PARAM_DATETIME_COMPONENT = "datetime";
    public const string PARAM_DATE_COMPONENT = "date";
    public const string PARAM_TIME_COMPONENT = "time";
    public const string PARAM_DROPDOWN_COMPONENT = "dropdown";
    public const string PARAM_CHECK_LIST_COMPONENT = "check_list";
    public const string PARAM_TOGGLE_COMPONENT = "toggle";
    public const string PARAM_TOGGLE_LIST_COMPONENT = "toggle_list";
    public const string PARAM_INPUTFIELD_COMPONENT = "inputfield";
    public const string PARAM_INPUTFIELD_MULTILINE_COMPONENT = "inputfield_multiline";
    public const string PARAM_ATTACHMENT_COMPONENT = "attachment";
}
